; Production tuning for orun-api-v2

memory_limit = 256M
post_max_size = 32M
upload_max_filesize = 32M
max_execution_time = 60
date.timezone = Europe/Paris
expose_php = Off

; opcache (tuned for prod)
opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 256
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 0
opcache.preload_user = www-data
; preload script can be added later via opcache.preload = /app/config/preload.php

; APCu
apc.enabled = 1
apc.enable_cli = 1

; Realpath cache
realpath_cache_size = 4096K
realpath_cache_ttl = 600
